kitchen/urls.py
from django.urls import path, include

from kitchen.views import (
    index,
    DishTypeListView,
    dish_type_detail_view,
    DishListView,
    DishDetailView,
    CookListView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    register_view,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-types-list"),
    path("dish-types/<int:pk>/", dish_type_detail_view, name="dish-type-detail"),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dishes/", DishListView.as_view(), name="dishes-list"),
    path("dishes/сreate/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("cooks/", CookListView.as_view(), name="cooks-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cooks-detail"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cooks-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cooks-delete"),
    path("cooks/create/", CookCreateView.as_view(), name="cooks-create"),
    path("register/", register_view, name="register"),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
]

templates/includes/footer.html
<ul class="pagination justify-content-center mt-4">
  {% include "includes/pagination.html" %}
</ul>

<footer class="footer pt-5 mt-5 text-center">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class="row">
      <div class="col-md-3 mb-4 mx-auto">
        <div>
          <h6 class="text-gradient text-primary font-weight-bolder">Restaurant Service</h6>
        </div>
        <div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12 mx-auto">
        <p class="my-4 text-sm">

          <a class="nav-link pe-1" href="https://github.com/kostomeister" target="_blank">
            by kostomeister <i class="fab fa-github text-lg opacity-8 align-middle"></i>
          </a>

        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-auth.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              TasteHeaven
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" href="https://github.com/app-generator/django-soft-ui-free" target="_blank">
                    <i class="fa fa-github me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Star us on Github">Github</p>
                  </a>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href="https://appseed.us/" 
                     class="btn btn-sm  bg-gradient-primary  btn-round mb-0 me-1 mt-2 mt-md-0">More Starters</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0">
    <div class="row">
        <div class="col-12">
            <nav class="navbar navbar-expand-lg blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
                <div class="container-fluid">
                    <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'kitchen:index' %}" rel="tooltip" title="To the main page" data-placement="bottom">
                        TasteHeaven
                    </a>
                    <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon mt-2">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </span>
                    </button>
                    <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
                        <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                            <li class="nav-item dropdown dropdown-hover mx-2">
                                <a href="{% url 'kitchen:dish-types-list' %}" class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center">
                                    Culinary Delights
                                </a>
                            </li>
                            <li class="nav-item dropdown dropdown-hover mx-2">
                                <a href="{% url 'kitchen:dishes-list' %}" class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center">
                                    Tasty Creations
                                </a>
                            </li>
                            <li class="nav-item dropdown dropdown-hover mx-2">
                                <a href="{% url 'kitchen:cooks-list' %}" class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center">
                                    More about our chefs
                                </a>
                            </li>
                            <li class="nav-item my-auto ms-lg-auto ms-3">

                                    {% if user.is_authenticated %}
                                      <a href="{% url 'logout' %}" class="btn btn-sm bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">
                                      Log Out
                                      </a>
                                    {% else %}
                                      <a href="{% url 'login' %}" class="btn btn-sm bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">
                                      Log In
                                      </a>
                                    {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination pagination-lg">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="/static/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="/static/assets/js/plugins/prism.min.js"></script>
  <script src="/static/assets/js/plugins/parallax.min.js"></script>