kitchen/urls.py
from django.urls import path, include

from kitchen.views import (
    index,
    DishTypeListView,
    dish_type_detail_view,
    DishListView,
    DishDetailView,
    CookListView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    register_view,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("dish-types/", DishTypeListView.as_view(), name="dish-types-list"),
    path("dish-types/<int:pk>/", dish_type_detail_view, name="dish-type-detail"),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dishes/", DishListView.as_view(), name="dishes-list"),
    path("dishes/сreate/", DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("cooks/", CookListView.as_view(), name="cooks-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cooks-detail"),
    path("cooks/<int:pk>/update/", CookUpdateView.as_view(), name="cooks-update"),
    path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cooks-delete"),
    path("cooks/create/", CookCreateView.as_view(), name="cooks-create"),
    path("register/", register_view, name="register"),
]

app_name = "kitchen"

kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
]

kitchen/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        verbose_name = "dish type"
        verbose_name_plural = "dish types"

    def __str__(self) -> str:
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"


class Dish(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE, related_name="dishes")
    cooks = models.ManyToManyField(get_user_model(), related_name="dishes")

    class Meta:
        verbose_name = "dish"
        verbose_name_plural = "dishes"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import DishType, Dish


class DishTypeForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = ["name"]


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CookForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
            "is_staff",
        )


class DishTypeSearchForm(forms.Form):
    dish_type = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Search by Dish Type"}),
        label="",
        required=False,
    )


class DishSearchForm(forms.Form):
    dish_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Search Dish by name"}),
        label="",
        required=False,
    )


class CookSearchForm(forms.Form):
    cook_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Search Cook by name"}),
        label="",
        required=False,
    )


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class CookUpdateForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "first_name", "last_name", "email", "years_of_experience")

kitchen/views.py
from django.contrib.auth import get_user_model, login
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

from .mixins.is_superuser import SuperUserCheckMixin

from kitchen.forms import (
    DishTypeForm,
    DishForm,
    DishTypeSearchForm,
    DishSearchForm,
    CookSearchForm,
    RegistrationForm,
    CookForm,
    CookUpdateForm,
)
from kitchen.models import Dish, DishType


def index(request: HttpRequest) -> HttpResponse:
    count_dishes = Dish.objects.count()
    count_cooks = queryset = get_user_model().objects.filter(
            Q(is_staff=True) & ~Q(is_superuser=True)
        ).count()
    count_dish_types = DishType.objects.count()
    context = {
        "count_dishes": count_dishes,
        "count_cooks": count_cooks,
        "count_dish_types": count_dish_types,
    }
    return render(request, "kitchen/index.html", context)


class DishTypeListView(generic.ListView):
    model = DishType
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        dish_type = self.request.GET.get("dish_type", "")
        context["dish_type_search_form"] = DishTypeSearchForm(
            initial={"dish_type": dish_type}
        )
        return context

    def get_queryset(self):
        dish_type = self.request.GET.get("dish_type")
        queryset = DishType.objects.all()
        if dish_type:
            queryset = queryset.filter(name__icontains=dish_type)
        return queryset


def dish_type_detail_view(request: HttpRequest, pk: int) -> HttpResponse:
    dish_type = get_object_or_404(DishType, pk=pk)
    dishes = dish_type.dishes.all()

    context = {
        "dish_type": dish_type,
        "dishes": dishes,
    }

    return render(request, "kitchen/dish_type_detail.html", context)


@method_decorator(staff_member_required, name="dispatch")
class DishTypeCreateView(generic.CreateView):
    model = DishType
    form_class = DishTypeForm
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-types-list")


@method_decorator(staff_member_required, name="dispatch")
class DishTypeUpdateView(generic.UpdateView):
    model = DishType
    form_class = DishTypeForm
    template_name = "kitchen/dish_type_form.html"

    def get_success_url(self):
        return reverse_lazy("kitchen:dish-type-detail", kwargs={"pk": self.object.pk})


@method_decorator(staff_member_required, name="dispatch")
class DishTypeDeleteView(generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-types-list")


class DishListView(generic.ListView):
    model = Dish
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        dish_name = self.request.GET.get("dish_name", "")
        context["dish_name_search_form"] = DishSearchForm(
            initial={"dish_name": dish_name}
        )
        return context

    def get_queryset(self):
        dish_name = self.request.GET.get("dish_name")
        queryset = Dish.objects.all()
        if dish_name:
            queryset = queryset.filter(name__icontains=dish_name)
        return queryset


class DishDetailView(generic.DetailView):
    model = Dish


@method_decorator(staff_member_required, name="dispatch")
class DishCreateView(generic.CreateView):
    model = Dish
    form_class = DishForm
    template_name = "kitchen/dish_form.html"
    success_url = reverse_lazy("kitchen:dishes-list")


@method_decorator(staff_member_required, name="dispatch")
class DishUpdateView(generic.UpdateView):
    model = Dish
    form_class = DishForm
    template_name = "kitchen/dish_form.html"

    def get_success_url(self):
        return reverse_lazy("kitchen:dish-detail", kwargs={"pk": self.object.pk})


@method_decorator(staff_member_required, name="dispatch")
class DishDeleteView(generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dishes-list")


class CookListView(generic.ListView):
    model = get_user_model()
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        cook_name = self.request.GET.get("cook_name", "")
        context["cook_search_form"] = CookSearchForm(initial={"cook_name": cook_name})
        return context

    def get_queryset(self):
        cook_name = self.request.GET.get("cook_name")
        queryset = get_user_model().objects.filter(
            Q(is_staff=True) & ~Q(is_superuser=True)
        )
        if cook_name:
            queryset = queryset.filter(
                Q(first_name__icontains=cook_name)
                | Q(last_name__icontains=cook_name)
                | Q(username__icontains=cook_name)
            )
        return queryset


class CookDetailView(generic.DetailView):
    model = get_user_model()


class CookCreateView(SuperUserCheckMixin, generic.CreateView):
    model = get_user_model()
    form_class = CookForm
    template_name = "kitchen/cook_form.html"
    success_url = reverse_lazy("kitchen:cooks-list")


class CookUpdateView(SuperUserCheckMixin, generic.UpdateView):
    model = get_user_model()
    form_class = CookUpdateForm
    template_name = "kitchen/cook_form.html"

    def get_success_url(self):
        return reverse_lazy("kitchen:cooks-detail", kwargs={"pk": self.object.pk})


class CookDeleteView(SuperUserCheckMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("kitchen:cooks-list")


def register_view(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/")
    else:
        form = RegistrationForm()

    return render(request, "registration/register.html", {"form": form})

templates/kitchen/cook_confirm_delete.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card" style="margin-top: 100px;">
                <div class="card-header">
                    <h2 class="text-center">Confirm Delete</h2>
                </div>
                <div class="card-body">
                    <p>Are you sure you want to delete the cook "{{ cook.first_name }} {{ cook.last_name }}"?</p>
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Yes, delete</button>
                        <a href="{% url 'kitchen:cooks-detail' pk=cook.id %}" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
  <div class="container mt-5 mb-5" style="padding-top: 100px">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-body">
            <h2 class="card-title">{{ cook.first_name }} {{ cook.last_name }}</h2>
            <h6 class="card-subtitle mb-2 text-muted">Username: {{ cook.username }}</h6>
            <h3 class="card-text">Years of Experience: {{ cook.years_of_experience }}</h3>
            <div class="mt-4">
              {% if user.is_superuser %}
              <a href="{% url 'kitchen:cooks-update' pk=cook.id %}" class="btn btn-primary">Update</a>
              <a href="{% url 'kitchen:cooks-delete' pk=cook.id %}" class="btn btn-danger">Delete</a>
              {% endif %}
            </div>

            <h5 class="mt-4">Dishes Participated:</h5>
            <ul class="list-group">
              {% for dish in cook.dishes.all %}
                <li class="list-group-item">
                  <a href="{% url 'kitchen:dish-detail' pk=dish.id %}" class="text-decoration-none">
                    {{ dish.name }}
                  </a>
                </li>
              {% empty %}
                <li class="list-group-item">This cook hasn't participated in any dishes yet.</li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/kitchen/cook_form.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-5 mb-5" style="padding-top: 100px">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">{{ object|yesno:"Update,Create" }} a Cook</h2>
            <form method="post" action="">
              {% csrf_token %}
              {{ form|crispy }}
              <div class="text-center">
                <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary btn-lg rounded-pill">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/kitchen/cook_list.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-5 mb-5 ">
    <div class="d-flex justify-content-between align-items-center mb-3" style="padding-top: 100px">
      <h2>List of Cooks</h2>
      {% if user.is_superuser %}
        <a href="{% url 'kitchen:cooks-create' %}" class="btn btn-primary">ADD NEW</a>
      {% endif %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <form action="" method="get" class="input-group rounded-0">
        {{ cook_search_form|crispy }}
        <span class="input-group-btn">
          <button type="submit" class="btn btn-default rounded-0">Search</button>
        </span>
      </form>
      {% for cook in cook_list %}
        <div class="col py-2">
          <div class="card h-100">
            <div class="card-body">
              <a href="{% url 'kitchen:cooks-detail' pk=cook.id %}">
                <h5 class="card-title">{{ cook.first_name }} {{ cook.last_name }}</h5>
                <p class="card-text">Years of Experience: {{ cook.years_of_experience }}</p>
                <h6 class="card-subtitle mb-2 text-muted">Dishes Participated:</h6>
                <ul>
                  {% for dish in cook.dishes.all|slice:":5" %}
                    <li>{{ dish.name }}</li>
                  {% endfor %}
                  {% if cook.dishes.count > 5 %}
                    <li>...</li>
                  {% endif %}
                  {% if not cook.dishes.all %}
                    <li>This cook hasn't participated in any dishes yet.</li>
                  {% endif %}
                </ul>
              </a>
            </div>
          </div>
        </div>
        {% empty %}
        <h3>No cooks were found!</h3>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/kitchen/dish_confirm_delete.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card" style="margin-top: 100px;">
                <div class="card-header">
                    <h2 class="text-center">Confirm Delete</h2>
                </div>
                <div class="card-body">
                    <p>Are you sure you want to delete the dish type "{{ dish.name }}"?</p>
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Yes, delete</button>
                        <a href="{% url 'kitchen:dish-type-detail' pk=dish.id %}" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card" style="margin-top: 100px;">
          <div class="card-header d-flex justify-content-between align-items-center">
              <h2 class="text-center">About {{ dish.name }}</h2>
              <div class="d-flex">
                {% if user.is_staff %}
                <a href="{% url 'kitchen:dish-update' pk=dish.id %}" class="btn btn-primary" style="margin-right: 0.5rem;">Update</a>
                {% endif %}
                {% if user.is_staff %}
                <a href="{% url 'kitchen:dish-delete' pk=dish.id%}" class="btn btn-danger">Delete</a>
                {% endif %}
              </div>
            </div>

          <div class="card-body">
            <p>{{ dish.description }}</p>
            <p><strong>Price:</strong> ${{ dish.price }}</p>
            <p>Type: {{ dish.dish_type.name }}</p>
            <div class="cooks-list">
              <p><strong>Cooks:</strong></p>
              <ul>
                {% for cook in dish.cooks.all %}
                  <li><a href="{% url 'kitchen:cooks-detail' pk=cook.id %}">
                    {{ cook.first_name }} {{ cook.last_name }}
                  </a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div class="container mt-5 mb-5" style="padding-top: 100px">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">{{ object|yesno:"Update,Create" }} a Dish</h2>
            <form method="post" action="">
              {% csrf_token %}
              {{ form|crispy }}
              <div class="text-center">
                <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary btn-lg rounded-pill">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/kitchen/dish_list.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-5 mb-5">
    <div class="row" style="margin-top: 100px;">
      <div class="col-12">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h2>List of Dishes</h2>
          {% if user.is_staff %}
            <a href="{% url 'kitchen:dish-create' %}" class="btn btn-primary">Add New</a>
          {% endif %}
        </div>
        <div class="row">
        <form action="" method="get" class="input-group">
          {{ dish_name_search_form|crispy }}
          <span class="input-group-btn">
            <button type="submit" class="btn btn-default">Search</button>
          </span>
        </form>
          {% for dish in dish_list|slice:":5" %}
            <div class="col-md-4 mb-4">
              <div class="card">
                <div class="card-body" style="height: 300px;">
                  <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">
                    <h4 class="card-title">{{ dish.name }}</h4>
                    <h6 class="text-muted">{{ dish.dish_type.name }}</h6>
                    {% if dish.description|wordcount > 20 %}
                      <p style="max-height: 80px; overflow: hidden;">{{ dish.description|truncatewords:20 }}</p>
                    {% else %}
                      {{ dish.description }}
                    {% endif %}
                    <p>Price: ${{ dish.price }}</p>
                  </a>
                </div>
              </div>
            </div>
            {% empty %}
        <h3>No dishes were found!</h3>
          {% endfor %}
          {% if dish_list|length > 5 %}
            <div class="col-12 text-center mt-3">
              <p>...</p>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/kitchen/dish_type_detail.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <div class="card" style="margin-top: 100px;">
          <div class="card-header d-flex justify-content-between align-items-center">
            <h2 class="text-center">Our {{ dish_type.name }}</h2>
            <div class="d-flex">
              {% if user.is_staff %}
              <a href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}" class="btn btn-primary me-2">Update</a>
              {% endif %}
              {% if user.is_staff %}
              <a href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}" class="btn btn-danger">Delete</a>
              {% endif %}
            </div>
          </div>
          <div class="card-body">
            <ul class="list-group">
              {% for dish in dishes %}
                <li class="list-group-item"><a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/kitchen/dish_type_form.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}


{% block content %}
  <div class="container mt-5 mb-5" style="padding-top: 100px">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card shadow">
          <div class="card-body">
            <h2 class="card-title text-center mb-4">{{ object|yesno:"Update,Create" }} a Dish Type</h2>
            <form method="post" action="">
              {% csrf_token %}
              {{ form|crispy }}
              <div class="text-center">
                <input type="submit" value="{{ object|yesno:"Update,Create" }}" class="btn btn-primary btn-lg rounded-pill">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/kitchen/dishtype_confirm_delete.html
{% extends "layouts/base-presentation.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card" style="margin-top: 100px;">
                <div class="card-header">
                    <h2 class="text-center">Confirm Delete</h2>
                </div>
                <div class="card-body">
                    <p>Are you sure you want to delete the dish type "{{ dishtype.name }}"?</p>
                    <form method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Yes, delete</button>
                        <a href="{% url 'kitchen:dish-type-detail' pk=dishtype.id %}" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/kitchen/dishtype_list.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-5 mb-5" style="padding-top: 100px">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h1>Our dish types</h1>

      {% if user.is_staff %}
        <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-primary">Add new</a>
      {% endif %}
    </div>
    <form action="" method="get" class="input-group">
      {{ dish_type_search_form|crispy }}
      <span class="input-group-btn">
          <button type="submit" class="btn btn-default">Search</button>
      </span>
    </form>
    <div class="row row-cols-md-3 g-4">
      {% for dish_type in dishtype_list %}
        <div class="col py-2">
          <div class="card h-100">
            <div class="card-body">
              <a href="{% url 'kitchen:dish-type-detail' pk=dish_type.id %}">
                <h4 class="card-title">{{ dish_type.name }}</h4>
                <ul>
                  {% for dish in dish_type.dish_set.all|slice:":5" %}
                    <li>{{ dish.name }}</li>
                    {% empty %}
                    <h7>No dishes in this dish type yet</h7>
                  {% endfor %}
                  {% if dish_type.dish_set.count > 5 %}
                    <li>...</li>
                  {% endif %}
                </ul>
              </a>
            </div>
          </div>
        </div>
        {% empty %}
        <h3>No dish types were found!</h3>
      {% endfor %}
    </div>
  </div>
{% endblock content %}